# Generated by Django 3.0.8 on 2020-07-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_auto_20200708_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='tipo_venda',
            field=models.IntegerField(choices=[(1, 'Atacado'), (2, 'Varejo')]),
        ),
    ]
