# Generated by Django 3.0.8 on 2020-07-08 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endereco_cliente', to='cliente.Endereco', verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sexo',
            field=models.IntegerField(choices=[(1, 'MASCULINO'), (2, 'FEMININO')], max_length=2, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'PESSOA FISICA'), (2, 'PESSOA JURIDICA')], max_length=2),
        ),
    ]
