# Generated by Django 3.0.8 on 2020-07-06 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('funcionario', '0001_initial'),
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateField(auto_now=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venda_cliente', to='cliente.Cliente', verbose_name='Categoria')),
                ('funcionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venda_funcionario', to='funcionario.Funcionario', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Vendas',
                'verbose_name_plural': 'Vendas',
            },
        ),
        migrations.CreateModel(
            name='VendasProd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendasprod_produto', to='produto.Produto', verbose_name='Produto')),
                ('venda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendasprod_venda', to='venda.Venda', verbose_name='Venda')),
            ],
        ),
    ]
