# Generated by Django 3.0.8 on 2020-07-08 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_auto_20200708_0932'),
        ('produto', '0002_auto_20200708_0932'),
        ('funcionario', '0002_auto_20200708_0932'),
        ('venda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venda_cliente', to='cliente.Cliente'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='funcionario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venda_funcionario', to='funcionario.Funcionario'),
        ),
        migrations.AlterField(
            model_name='vendasprod',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendasprod_produto', to='produto.Produto'),
        ),
        migrations.AlterField(
            model_name='vendasprod',
            name='venda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendasprod_venda', to='venda.Venda'),
        ),
    ]
