# Generated by Django 3.0.8 on 2020-07-06 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('tipo', models.IntegerField(choices=[(1, 'Vendas Externas'), (2, 'Vendas Internas')], max_length=1, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sexo', models.IntegerField(choices=[(1, 'MASCULINO'), (2, 'FEMININO')], max_length=1, verbose_name='Sexo')),
                ('data_nasc', models.DateField()),
                ('cpf', models.PositiveIntegerField()),
                ('setor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funcionario_setor', to='funcionario.Setor', verbose_name='Setor')),
            ],
        ),
    ]
