# Generated by Django 3.0.8 on 2020-07-08 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='setor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funcionario_setor', to='funcionario.Setor'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='sexo',
            field=models.IntegerField(choices=[(1, 'MASCULINO'), (2, 'FEMININO')], max_length=1),
        ),
        migrations.AlterField(
            model_name='setor',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='setor',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Vendas Externas'), (2, 'Vendas Internas')], max_length=1),
        ),
    ]
