# Generated by Django 3.0.8 on 2020-07-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0002_auto_20200708_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='sexo',
            field=models.IntegerField(choices=[(1, 'MASCULINO'), (2, 'FEMININO')]),
        ),
        migrations.AlterField(
            model_name='setor',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Vendas Externas'), (2, 'Vendas Internas')]),
        ),
    ]
